---
core:
   # Number of Nornir worker threads that are run at the same time - default is 20
    num_workers: 30

inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "inventory/hosts.yaml"
        group_file: "inventory/groups.yaml"
        defaults_file: "inventory/defaults.yaml"

logging:
    enabled: True
    level: INFO
    file: "nornir.log"
